export const PAGE_STATE = {
	PREPARING: "PREPARING",
	LOADING: "LOADING",
	RUNNING: "RUNNING",
	FINISHING: "FINISHING"
}

export const GAME_TYPES = {
	WORDS: "WORDS",
	PICTURES: "PICTURES",
	SOMETHING: "SOMETHING",
}

export const VIEWPORTS = {
	SMALL:576,
	MEDIUM:768,
	LARGE:992,
	XLARGE:1200,
	XXLARGE:1400,
}

export const ITEM_STATUS = {
	ADDED: "ADDED",
	DELETED: "DELETED",
	CHANGED: "CHANGED",
	INITIAL: "INITIAL"
}

